export const CREATE_BOARD_SUCCESS = 'CREATE_BOARD_SUCCESS';
export const CREATE_BOARD_FAILURE = 'CREATE_BOARD_FAILURE';

export const EDIT_STACK_SUCCESS = 'EDIT_STACK_SUCCESS';
export const EDIT_STACK_FAILURE = 'EDIT_STACK_FAILURE';

export const DELETE_STACK_SUCCESS = 'DELETE_STACK_SUCCESS';
export const DELETE_STACK_FAILURE = 'DELETE_STACK_FAILURE';