export const FETCH_BOARD_DETAILS         = 'FETCH_BOARD_DETAILS';
export const FETCH_BOARD_DETAILS_SUCCESS = 'FETCH_BOARD_DETAILS_SUCCESS';

export const EDIT_STACK_SUCCESS = 'EDIT_STACK_SUCCESS';
export const EDIT_STACK_FAILURE = 'EDIT_STACK_FAILURE';