export const GET_BOARD_LIST         = 'GET_BOARD_LIST';
export const GET_BOARD_LIST_SUCCESS = 'GET_BOARD_LIST_SUCCESS';
export const GET_BOARD_LIST_FAILURE = 'GET_BOARD_LIST_FAILURE';

export const SAVE_BOARD_SUCCESS = 'SAVE_BOARD_SUCCESS';
export const SAVE_BOARD_FAILURE = 'SAVE_BOARD_FAILURE';

