export const GET_BOARD_LIST         = 'GET_BOARD_LIST';
export const GET_BOARD_LIST_SUCCESS = 'GET_BOARD_LIST_SUCCESS';
export const GET_BOARD_LIST_FAILURE = 'GET_BOARD_LIST_FAILURE';

export const SAVE_BOARD_SUCCESS = 'SAVE_BOARD_SUCCESS';
export const SAVE_BOARD_FAILURE = 'SAVE_BOARD_FAILURE';

export const CREATE_BOARD_SUCCESS = 'CREATE_BOARD_SUCCESS';
export const CREATE_BOARD_FAILURE = 'CREATE_BOARD_FAILURE';

export const DELETE_BOARD_SUCCESS = 'DELETE_BOARD_SUCCESS';
export const DELETE_BOARD_FAILURE = 'DELETE_BOARD_FAILURE';
