export const CREATE_CARD_SUCCESS = 'CREATE_CARD_SUCCESS';
export const CREATE_CARD_FAILURE = 'CREATE_CARD_FAILURE';

export const DELETE_CARD_SUCCESS = 'DELETE_CARD_SUCCESS';
export const DELETE_CARD_FAILURE = 'DELETE_CARD_FAILURE';

export const MOVE_CARD_SUCCESS = 'MOVE_CARD_SUCCESS';
export const MOVE_CARD_FAILURE = 'MOVE_CARD_FAILURE';